apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexora-control-plane
  namespace: nexora-system
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.nexora.red
      secretName: app-nexora-red-tls
  rules:
    - host: app.nexora.red
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexora-control-plane
                port:
                  number: 80
    - host: "*.nexora.red"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexora-control-plane
                port:
                  number: 80
