apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexora-control-plane
  namespace: nexora-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexora-control-plane
  namespace: odoo-system
rules:
  - apiGroups: [""]
    resources: ["services", "secrets", "persistentvolumeclaims", "configmaps", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexora-control-plane
  namespace: odoo-system
subjects:
  - kind: ServiceAccount
    name: nexora-control-plane
    namespace: nexora-system
roleRef:
  kind: Role
  name: nexora-control-plane
  apiGroup: rbac.authorization.k8s.io
